### ISSUE TITLE
Error enabling Gtranslate

### ISSUE THREAD

**Issue by alfahadgm** [AzC0de/ChatTranslatorPlugin#1]
Hi I configured the yml but I have error when it starts. Paper version 1.19.4

````
[07:57:16] [Server thread/INFO]: [GlobalTranslate] Enabling GlobalTranslate v1.0
[07:57:16] [Server thread/WARN]: [GlobalTranslate] Could not save messages.yml to plugins\GlobalTranslate\messages.yml because messages.yml already exists.
[07:57:16] [Server thread/WARN]: [com.google.cloud.translate.TranslateOptions] Ignoring Application Default Credentials GOOGLE_APPLICATION_CREDENTIALS: using explicit setting for API key instead.
[07:57:16] [Server thread/ERROR]: Error occurred while enabling GlobalTranslate v1.0 (Is it up to date?)
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:418) ~[snakeyaml-1.33.jar:?]
	at us.azcode.GTranslate.papi.GTranslateIntegration$TranslationManager.loadTranslations(GTranslateIntegration.java:46) ~[GTranslate-1.0.jar:?]
	at us.azcode.GTranslate.papi.GTranslateIntegration.setup(GTranslateIntegration.java:35) ~[GTranslate-1.0.jar:?]
	at us.azcode.GTranslate.papi.GTranslateIntegration.<init>(GTranslateIntegration.java:26) ~[GTranslate-1.0.jar:?]
	at us.azcode.GTranslate.GlobalTranslate.onEnable(GlobalTranslate.java:93) ~[GTranslate-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:176) ~[snakeyaml-1.33.jar:?]
	... 29 more
```

**Comment by AzC0de** [comment]
Could you pass me the .yml that you modified?

**Comment by AzC0de** [comment]
> Hi I configured the yml but I have error when it starts. Paper version 1.19.4
> 
> `[07:57:16] [Server thread/INFO]: [GlobalTranslate] Enabling GlobalTranslate v1.0 [07:57:16] [Server thread/WARN]: [GlobalTranslate] Could not save messages.yml to plugins\GlobalTranslate\messages.yml because messages.yml already exists. [07:57:16] [Server thread/WARN]: [com.google.cloud.translate.TranslateOptions] Ignoring Application Default Credentials GOOGLE_APPLICATION_CREDENTIALS: using explicit setting for API key instead. [07:57:16] [Server thread/ERROR]: Error occurred while enabling GlobalTranslate v1.0 (Is it up to date?) org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1 at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.Yaml.load(Yaml.java:418) ~[snakeyaml-1.33.jar:?] at us.azcode.GTranslate.papi.GTranslateIntegration$TranslationManager.loadTranslations(GTranslateIntegration.java:46) ~[GTranslate-1.0.jar:?] at us.azcode.GTranslate.papi.GTranslateIntegration.setup(GTranslateIntegration.java:35) ~[GTranslate-1.0.jar:?] at us.azcode.GTranslate.papi.GTranslateIntegration.<init>(GTranslateIntegration.java:26) ~[GTranslate-1.0.jar:?] at us.azcode.GTranslate.GlobalTranslate.onEnable(GlobalTranslate.java:93) ~[GTranslate-1.0.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.nio.charset.MalformedInputException: Input length = 1 at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?] at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?] at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?] at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?] at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118) ~[snakeyaml-1.33.jar:?] at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:176) ~[snakeyaml-1.33.jar:?] ... 29 more`

Could you pass me the .yml that you modified?

**Comment by alfahadgm** [comment]
Actually the Error shows with default configurations so the yml does not affect. the following is for config.yml
```
api-key: "xxxxxxxxxx"
chat-format: "{g:blue-to-green}%player_displayname%{/g}&r: {g:ocean}%message%{/g}"
gc-cooldown-seconds: 5
use-cache: true
showWelcomeMessage: false # Do not activate, implementation not completed
# 'sqlite' or 'mysql'
database:
  type: 'mysql'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'gtranslate'
    username: 'root'
    password: 'xxxxxxx'
gradients:
  blue-to-green:
    text: "Blue to green"
    startColor: "#0072c6"
    endColor: "#8cc63e"
  ocean:
    text: "Ocean"
    startColor: "#00b4db"
    endColor: "#0083b0"

```
